# Generated by Django 5.1.7 on 2025-04-07 22:41

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_organization_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='org_logos/', validators=[app.models.validate_image_type, app.models.validate_image_size]),
        ),
    ]
