# Generated by Django 5.1.7 on 2025-05-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_customuser_position_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
